### ISSUE TITLE
Module problems

### ISSUE THREAD

**Issue by 555dexter111** [tradetracker-com/magento2#2] opened 2021-05-12 07:31 UTC
Hi,
We found the next problems:
- it is not compatible with Magento Commerce at all:
 * feeds contains incorrect data (URL, category, image, etc)
 * there is usage of product entity_id instead of row_id (`TradeTracker\Connect\Service\ProductData\AttributeCollector\Data\Parents::collectAllParents`, etc)
- sometimes Magento has empty values in attribute in tables (catalog_product_entity_*). There is no validation for such cases  `TradeTracker\Connect\Service\ProductData\AttributeCollector\Data\AttributeMapper::collectAttributeValues`
- it does not work with store level - it generate feeds only for global level. So in the resulting XML files there are all products

Please inform when you are going to make a new realize with these fixes.

**Comment by Marvin-Magmodules** [comment] 2021-05-25 11:56
Hi @555dexter111, thank you for opening his issue. We have just releases the [v1.1.0](https://github.com/tradetracker-com/magento2/releases/tag/v1.1.0) version that fixes the identity issue in EE (/w content staging). This was already implemented but was missing in two places. Also the Website separation for products was fixed in this release. We were not able to reproduce the other issues, could be these were related to the above two issues. Can you let us know your findings?

**Comment by Marvin-Magmodules** [comment] 2021-07-13 17:07
Hi @555dexter111, any update on this issue?

**Comment by Marvin-Magmodules** [comment] 2021-11-01 12:29
Closing issue due to inactivity. If this issue still occurs, please reopen this issue of send us an email though our contact form: https://www.magmodules.eu/support-form.html

**Closed as completed by Marvin-Magmodules** 2021-11-01 12:29 UTC
